import type {Config} from "tailwindcss";
import {plugin, content} from "flowbite-react/tailwind";

export default {
    content: [
        "./pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./components/**/*.{js,ts,jsx,tsx,mdx}",
        "./app/**/*.{js,ts,jsx,tsx,mdx}",
        content(),
    ],
    theme: {
        extend: {
            colors: {
                background: "var(--background)",
                foreground: "var(--foreground)",
            },
        },
    },
    plugins: [
        plugin(),
    ],
    safelist: [
        'bg-gray-100',
        'border-gray-200',
        'bg-blue-100',
        'border-blue-200',
        'bg-green-100',
        'border-green-200',
        'bg-red-100',
        'border-red-200',
        'bg-purple-100',
        'border-purple-200',
        'bg-pink-100',
        'border-pink-200',
        'bg-indigo-100',
        'border-indigo-200',
        'bg-teal-100',
        'border-teal-200',
        'bg-orange-100',
        'border-orange-200',
        'bg-amber-100',
        'border-amber-200',
        'bg-lime-100',
        'border-lime-200',
        'bg-emerald-100',
        'border-emerald-200',
        'bg-cyan-100',
        'border-cyan-200',
        'bg-sky-100',
        'border-sky-200',
        'bg-violet-100',
        'border-violet-200',
        'bg-fuchsia-100',
        'border-fuchsia-200',
        'bg-rose-100',
        'border-rose-200',
        'bg-slate-100',
        'border-slate-200',
        'bg-zinc-100',
        'border-zinc-200',
        'bg-stone-100',
        'border-stone-200',
        'bg-neutral-100',
        'border-neutral-200',
        'bg-yellow-100',
        'border-yellow-200',
    ],
} satisfies Config;
